```
kind: Service
apiVersion: v1
metadata:
    name: helloworldservice
spec:
    selector:
            app: hello-world
    ports:
        - protocol: "TCP"
          port: 8080
          targetPort: 80
          nodePort: 300001
    type: loadBalancer



```
apiVersion: apps/v1
kind: Deployment
metadata:
    name: hello-world
    labels:
        app: nginx
spec:
    replicas: 5
    template:
        metadata:
            labels:
                app: hello-world
        spec:
            containers:
                - name: tutum/hello-world
                  ports:
                      - containerPort: 80
